matrix:
  fast_finish: true

image:
  - Visual Studio 2017

platform: x64

version: '{build}-{branch}'

environment:
  CMAKE_SYSTEM_VERSION: 10.0.17134.0
  PACKAGE_PREFIX: amd-encoder-for-obs-studio
  INNOSETUP_URL: http://www.jrsoftware.org/download.php/is-unicode.exe
  CURL_VERSION: 7.39.0
  
install:
- cmd: ci/appveyor-install.bat

build_script:
- cmd: ci/appveyor-build.bat

after_build:
- cmd: ci/appveyor-package.bat

cache:
  - inno.exe

artifacts:
  - path: build/obs-stream-effects-*.zip
  - path: build/obs-stream-effects-*.7z
  - path: build/obs-stream-effects-*.exe

deploy:
  - provider: GitHub
    auth_token:
      secure: QwBI/KNma7xeTcwQUGpTNSFaZU13Qv9UpiqUKHndJgAsh3aoRM8jnGUvCcg8aQIO
    draft: true
    prerelease: false
    force_update: true
    on:
      appveyor_repo_tag: true

test: off

notifications:
  - provider: Webhook
    url: 
      secure: PTtt5ALhmK0q42jYyx4/Qa1Uf18+gLMXKGdzJjDISJt8IE/K0Zyp58UYmDDbbyLp4pBRf/Ylj8rn/zYL/mqBoDVRIH5zasPqIvBD0ZhtvNjTOxQ3QoRkAmxgpWeMowm3A3I1rLizA2H4EctPpoAJGrvQ1G2HEYn9tVsGYeetFTo=
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
    body: >-
      {
        "content": "**Build {{status}}**: {{buildUrl}}\n[{{commitId}}] {{commitMessage}}\nBy {{commitAuthor}} on {{commitDate}}"
      }